title = "Custom Gitleaks Config"

[[rules]]
id = "generic-api-key"
description = "Generic API Key Detection"
regex = '''(?i)(api|key|token|secret)[\s:=]+[A-Za-z0-9_\-]{10,}'''
tags = ["key", "API", "token"]
